service: hstest-int-stock

configValidationMode: error

package:
  individually: true
  patterns:
    - src/**/*.js
    - src/**/*.js.map

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    sourcesContent: false

plugins:
  - '@aligent/serverless-conventions'
  - serverless-esbuild
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  memorySize: 192 #mb (default for all)
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_OPTIONS: --enable-source-maps
  iam:
    Effect: Allow
    Action:
      - s3:*
    Resource: 'arn:aws:s3:::${self:service}-${self:provider.stage}-bucket/*'

functions:
  getProductUpdates:
    handler: src/lambda/get-product-updates.handler
  world:
    handler: src/lambda/world.handler

stepFunctions:
  validate: true
  stateMachines:
    helloWorld:
      name: ${self:service}-${self:provider.stage}-helloWorld
      tracingConfig:
        enabled: true
      definition:
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource:
              Fn::GetAtt: [hello, Arn]
            Next: World
          World:
            Type: Task
            Resource:
              Fn::GetAtt: [world, Arn]
            Next: Passthru
          Passthru:
            Type: Pass
            Next: Stop
          Stop:
            Type: Pass
            End: true

resources:
  Description: Harmony to Shopify Test Inventory Delta Service
  Resources:
    Storage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-bucket

