service: hstest-int-stock

configValidationMode: error

package:
  individually: true
  patterns:
    - src/**/*.js
    - src/**/*.js.map

custom:
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    sourcesContent: false

plugins:
  - '@aligent/serverless-conventions'
  - serverless-esbuild
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  memorySize: 192 #mb (default for all)
  tracing:
    apiGateway: true
    lambda: true
  environment:
    NODE_OPTIONS: --enable-source-maps
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: 'arn:aws:s3:::${self:service}-${self:provider.stage}-bucket/*'

functions:
  getProductUpdates:
    handler: src/lambda/get-product-updates.handler
    environment:
      s3BucketName: '${self:service}-${self:provider.stage}-bucket'
  getSkus:
    handler: src/lambda/get-skus.handler
    environment:
      s3BucketName: '${self:service}-${self:provider.stage}-bucket'

stepFunctions:
  validate: true
  stateMachines:
    deltaStockSync:
      name: ${self:service}-${self:provider.stage}-deltaStockSync
      tracingConfig:
        enabled: true
      events:
        - schedule:
          name: 15-min-stock-delta
          description: 'The event to make the delta stock sync run every 15 minutes'
          rate: rate(15 minutes)
          enabled: true
      definition:
        StartAt: getProductUpdates
        States:
          getProductUpdates:
            Type: Task
            Resource:
              Fn::GetAtt: [getProductUpdates, Arn]
            Next: getSkus
          getSkus:
            Type: Task
            Resource:
              Fn::GetAtt: [getSkus, Arn]
            Next: Stop
          Stop:
            Type: Pass
            End: true

resources:
  Description: Harmony to Shopify Test Inventory Delta Service
  Resources:
    Storage:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-bucket

